---
  - name: Check if su exist
    stat:
      path: /usr/bin/su
    register: file_su
    tags: elastic_install
  - name: Check if sudo exist
    stat:
      path: /usr/bin/sudo
    register: file_sudo
    tags: elastic_install
  # - name: Update intermediate certificates to certificate bundle
  #   become: yes
  #   become_method: su
  #   command: /usr/sbin/update-ca-certificates
  #   when: f.stat.exists
  # - name: Upload tar.gz Elasticsearch from remote URL
  #   get_url:
  #     url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
  #     dest: "/tmp/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
  #     mode: 0755
  #     timeout: 60
  #     force: true
  #     validate_certs: no
  #   register: get_elastic
  #   until: get_elastic is succeeded
  #   tags: elastic_install

  - name: Add the group elastic_group with sudo
    become: yes
    become_method: sudo
    ansible.builtin.group:
      name: "{{ elastic_group }}"
      state: present
    tags:
      - elastic_install
    when: file_sudo.stat.exists

  - name: Add the group elastic_group with su
    become: yes
    become_method: su
    ansible.builtin.group:
      name: "{{ elastic_group }}"
      state: present
    tags:
      - elastic_install
    when: file_su.stat.exists and not file_sudo.stat.exists

  - name: Add the user elastic_user with sudo
    become: yes
    become_method: sudo
    ansible.builtin.user:
      name: "{{ elastic_user }}"
    tags:
      - elastic_install
    when: file_sudo.stat.exists

  - name: Add the user elastic_user with su
    become: yes
    become_method: su
    ansible.builtin.user:
      name: "{{ elastic_user }}"
    tags:
      - elastic_install
    when: file_su.stat.exists and not file_sudo.stat.exists


  - name: copy tar.gz Elastic with sudo
    become: yes
    become_method: sudo
    ansible.builtin.copy:
      src: "files/elasticsearch-{{ elastic_version }}-linux-{{ host_platform }}.tar.gz"
      dest: "/tmp/elasticsearch-{{ elastic_version }}-linux-{{ host_platform }}.tar.gz"
      mode: 0755
      owner: "{{ elastic_user }}"
      group: "{{ elastic_group }}"
      force: true
    register: get_elastic
    until: get_elastic is succeeded
    tags:
      - elastic_install
    when: file_sudo.stat.exists

  - name: copy tar.gz Elastic with su
    become: yes
    become_method: su
    ansible.builtin.copy:
      src: "files/elasticsearch-{{ elastic_version }}-linux-{{ host_platform }}.tar.gz"
      dest: "/tmp/elasticsearch-{{ elastic_version }}-linux-{{ host_platform }}.tar.gz"
      mode: 0755
      owner: "{{ elastic_user }}"
      group: "{{ elastic_group }}"
      force: true
    register: get_elastic
    until: get_elastic is succeeded
    tags:
      - elastic_install
    when: file_su.stat.exists and not file_sudo.stat.exists

  - name: Create directrory for Elasticsearch with sudo if not su
    become: yes
    become_method: sudo
    file:
      state: directory
      path: "{{ elastic_home }}"
      owner: "{{ elastic_user }}"
      group: "{{ elastic_group }}"
      mode: 0755
    tags: elastic_install
    when: file_sudo.stat.exists

  - name: Create directrory for Elasticsearch with su
    become: yes
    become_method: su
    file:
      state: directory
      path: "{{ elastic_home }}"
      owner: "{{ elastic_user }}"
      group: "{{ elastic_group }}"
      mode: 0755
    tags: elastic_install
    when: file_sudo.stat.exists and not file_sudo.stat.exists

  - name: Extract Elasticsearch in the installation directory with sudo if not su
    become: yes
    become_method: sudo
    unarchive:
      copy: false
      src: "/tmp/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
      dest: "{{ elastic_home }}"
      extra_opts: [--strip-components=1]
      creates: "{{ elastic_home }}/bin/elasticsearch"
    tags:
      - skip_ansible_lint
      - elastic_install
    when: file_sudo.stat.exists

  - name: Extract Elasticsearch in the installation directory with su
    become: yes
    become_method: su
    unarchive:
      copy: false
      src: "/tmp/elasticsearch-{{ elastic_version }}-linux-x86_64.tar.gz"
      dest: "{{ elastic_home }}"
      extra_opts: [--strip-components=1]
      creates: "{{ elastic_home }}/bin/elasticsearch"
    tags:
      - skip_ansible_lint
      - elastic_install
    when: file_su.stat.exists and not file_su.stat.exists
    register: download_result
  
  - name: Set environment Elastic with sudo
    become: yes
    become_method: sudo
    template:
      src: templates/elk.sh.j2
      dest: /etc/profile.d/elk.sh
    tags: elastic_install
    when: file_sudo.stat.exists
  
  - name: Set environment Elastic with su
    become: yes
    become_method: su
    template:
      src: templates/elk.sh.j2
      dest: /etc/profile.d/elk.sh
    tags: elastic_install
    when: file_su.stat.exists and not file_su.stat.exists
